# Laravel recipe
name: icecomet2

# Start with the default laravel recipe
recipe: laravel

# Configure the Laravel recipe
config:

  # See: https://laravel.com/docs/5.6/installation#server-requirements

  # Optionally specify the php version to use.
  #
  # If ommitted this will default to the latest php version supported by Laravel.
  # Consult the `php` service to see what versions are available. Note that all
  # such versions may not be supported in Laravel 7 so YMMV.
  #
  # See: https://laravel.com/docs/5.6/installation#server-requirements
  #
  # NOTE: that this needs to be wrapped in quotes so that it is a string
  #
  php: '7.1'

  # Optionally specify whether you want to serve Laravel via Nginx or Apache
  #
  # If ommitted this will default to the latest apache
  #
  # See: https://laravel.com/docs/5.6/installation#web-server-configuration
  #
  via: nginx
  # Optionally specify the location of the webroot relative to your approot.
  # For Laravel this is usually 'public'
  #
  # If ommitted this will be your approot itself.
  #
  webroot: root/public

  # Optionally specify a primary database, this can be one of:
  #
  #   - `mysql`
  #   - `mariadb`
  #   - `postgres`
  #
  # If ommitted this will not install a db for you.
  #
  # see: https://laravel.com/docs/5.6/database#configuration
  #
  database: mysql

  # Optionally specify a primary caching backend, this can be one of:
  #
  #   - `redis`
  #   - `memcached`
  #
  # If ommitted this will not install a db for you
  #
  # see: https://laravel.com/docs/5.6/cache#configuration
  cache: redis

  # Optionally activate xdebug
  #
  # If you are having trouble getting xdebug to work please see:
  # https://docs.devwithlando.io/services/php.html#using-xdebug
  xdebug: true

  # Optionally mix in your own config files
  #
  # If ommitted this will use "sane defaults" for your recipe type
  # conf:

    # For more information on setting these files check out the documentation
    # and examples
    #
    # Docs: https://docs.devwithlando.io/services/php.html
    # Examples: https://github.com/lando/lando/tree/master/examples
    #
    # server: config/laravel.conf
    # php: config/php.ini

    # For more information on setting these files check out the documentation
    # and examples for the relevant services:
    #
    # MySQL: https://docs.devwithlando.io/services/mysql.html
    # MariaDB: https://docs.devwithlando.io/services/mariadb.html
    # PostGres: https://docs.devwithlando.io/services/postgres.html
    #
    # Examples: https://github.com/lando/lando/tree/master/examples
    #
    # database: config/mysql
    # Optionally use our own config files

  # conf:

  #   # For more information on setting these files check out the documentation
  #   # and examples
  #   #
  #   # Docs: https://docs.devwithlando.io/services/php.html
  #   # Examples: https://github.com/lando/lando/tree/master/examples
  #   #
  #   server: config/nginx.conf 

# services:

#   # Create an nginx service called "appserver"
#   appserver:

#     # Use nginx version 1.12
#     type: nginx:1.12

#     # Optionally specify a webroot if your index.html is in a subdirectory
#     webroot: root/public

#     # Optionally use our own config files
#     config:

#       # Use custom nginx server config located in config/server.conf relative
#       # to our app root
#       server: config/server.conf


tooling:

  # Define `lando composer` as a command that runs `composer --ansi @` against
  # the appserver service. Note that @ will be any additional arguments you pass
  # into `lando composer`
  #
  # Example: typing `lando composer install` will run `composer --ansi install`
  # inside the container.
  composer:
    service: appserver

  php:
    service: appserver
  artisan:
    service: appserver
